apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/codefresh/argo-events
  newName: custom_registry/argo-events
  newTag: v1.7.2-cap-CR-14600

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: controller-manager
    namespace: argo-events
  spec:
    template:
      spec:
        containers:
        - name: controller-manager
          env:
          - name: ARGO_EVENTS_IMAGE
            value: custom_registry/argo-events:v1.7.2-cap-CR-14600
- |-
  apiVersion: v1
  data:
    controller-config.yaml: |
      eventBus:
        nats:
          versions:
          - version: 0.22.1
            natsStreamingImage: custom_registry/nats-streaming:0.22.1
            metricsExporterImage: custom_registry/prometheus-nats-exporter:0.8.0
        jetstream:
          # Default JetStream settings, could be overridden by EventBus JetStream specs
          settings: |
            # https://docs.nats.io/running-a-nats-service/configuration#jetstream
            # Only configure "max_memory_store" or "max_file_store", do not set "store_dir" as it has been hardcoded.
            # e.g. 1G. -1 means no limit, up to 75% of available memory
            max_memory_store: -1
            # e.g. 20G. -1 means no limit, Up to 1TB if available
            max_file_store: 1TB
          streamConfig: |
            # The default properties of the streams to be created in this JetStream service
            maxMsgs: 50000
            maxAge: 168h
            maxBytes: -1
            replicas: 3
            duplicates: 300s
          versions:
          - version: latest
            natsImage: custom_registry/nats:2.8.1
            metricsExporterImage: custom_registry/prometheus-nats-exporter:0.9.1
            configReloaderImage: custom_registry/nats-server-config-reloader:0.7.0
            startCommand: /nats-server
          - version: 2.8.1
            natsImage: custom_registry/nats:2.8.1
            metricsExporterImage: custom_registry/prometheus-nats-exporter:0.9.1
            configReloaderImage: custom_registry/nats-server-config-reloader:0.7.0
            startCommand: /nats-server
          - version: custom_registry/2.8.1-alpine
            natsImage: custom_registry/nats:2.8.1-alpine
            metricsExporterImage: custom_registry/prometheus-nats-exporter:0.9.1
            configReloaderImage: custom_registry/nats-server-config-reloader:0.7.0
            startCommand: nats-server
          - version: 2.8.2
            natsImage: custom_registry/nats:2.8.2
            metricsExporterImage: custom_registry/prometheus-nats-exporter:0.9.1
            configReloaderImage: custom_registry/nats-server-config-reloader:0.7.0
            startCommand: /nats-server
          - version: 2.8.2-alpine
            natsImage: custom_registry/nats:2.8.2-alpine
            metricsExporterImage: custom_registry/prometheus-nats-exporter:0.9.1
            configReloaderImage: custom_registry/nats-server-config-reloader:0.7.0
            startCommand: nats-server
  kind: ConfigMap
  metadata:
    name: argo-events-controller-config
    namespace: argo-events

resources:
- github.com/codefresh-io/csdp-official/csdp/hybrid/basic/apps/argo-events?ref=0.1.20
