apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/codefresh/argocli
  newName: custom_registry/argocli
  newTag: v3.4-cap-CR-15902
- name: quay.io/codefresh/argoexec
  newName: custom_registry/argoexec
  newTag: v3.4-cap-CR-15902
- name: quay.io/codefresh/workflow-controller
  newName: custom_registry/workflow-controller
  newTag: v3.4-cap-CR-15902

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: workflow-controller
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/args/3
      value: custom_registry/argoexec:v3.4-cap-CR-15902

resources:
- github.com/codefresh-io/csdp-official.git/csdp/hybrid/basic/apps/argo-workflows?ref=0.1.20
